# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20170110_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='object_id',
            field=models.CharField(max_length=50),
        ),
    ]
